name: sismos_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flag: ^6.0.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.18.0
  logging: ^1.1.1
  provider: ^6.0.5
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
