name: quizz_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  path: any
  csv: ^5.0.1
  flutter:
    sdk: flutter
  http: ^0.13.5
  stop_watch_timer: ^2.0.0
  timer_count_down: ^2.2.2
  pull_to_refresh: ^2.0.0
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: "assets/logo.png" 
  android: true
  ios: true